site_name: Event Driven Automation Experience
nav:
  - Welcome: index.md
  - Lab 1: lab1.md
  - Lab 2: lab2.md
  - Lab 3: lab3.md
  - Lab 4: lab4.md

site_author: Nokia
site_description: >-
  EDA is the platform for automating your infrastructure.
# Repository
repo_name: docs
repo_url: https://github.com/nokia-eda/docs
edit_uri: edit/main/docs/
site_url: "https://docs.eda.dev"
copyright: Copyright &copy; 2024 Nokia
theme:
  name: material
  custom_dir: docs/overrides

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  features:
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - search.suggest
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.action.edit
    - toc.follow
    - content.tooltips
    - content.footnote.tooltips
    - navigation.indexes

  language: en
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: NokiaPureText
    code: Fira Code
  icon:
    logo: nokia/eda
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
  favicon: images/eda.svg

# Plugins
plugins:
  - meta
  - glightbox

  - tags
  - typeset
  - search
  - minify:
      minify_html: true
  - social:
      enabled: !ENV [CI, false]
      # enabled: true
      # debug: true
      # debug_color: yellow
      cards_layout: custom

# Customization
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://eda.dev/discord
    - icon: fontawesome/brands/github
      link: https://github.com/nokia-eda/docs
  annotate:
    bash:
      - .s1
      - .s2

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.md_in_html
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - toc:
      permalink: "#"
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      line_spans: __span
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: nokia-eda
      repo: docs
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
      url_download: true
      dedent_subsections: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.blocks.admonition
  - pymdownx.blocks.definition
  - pymdownx.blocks.details
  - pymdownx.blocks.html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - stylesheets/nokia.css
  - stylesheets/nokia-fonts.css
  - stylesheets/diagrams.css
  - stylesheets/animations.css
