apiVersion: notifiers.eda.nokia.com/v1
kind: Notifier
metadata:
  name: new-lldp-neighbor
spec:
  description: "Notifier for new LLDP neighbors"
  enabled: true
  sources:
    query:
      table: .db.cr-status.interfaces_eda_nokia_com.v1alpha1.interface.status.members.neighbors
      fields:
      - .db.cr-status.interfaces_eda_nokia_com.v1alpha1.interface.name
      - interface
      - node
      title: >-
        LLDP neighbor - 
        {{ index . ".db.cr-status.interfaces_eda_nokia_com.v1alpha1.interface.name" }} 
        -> {{ index . "node" }}-{{ index . "interface" }}"
      template: >- 
        "A new LLDP neighbor has appeared on interface 
        {{ index . \".db.cr-status.interfaces_eda_nokia_com.v1alpha1.interface.name\" }}: 
        host name {{ index . \"node\" }}, interface name {{ index . \"interface\" }}"
  providers:
  - discord